-- ============================================================================
-- 001_create_leads_table.sql
--
-- Run this ONCE in the Supabase SQL Editor (Dashboard → SQL Editor → New query
-- → paste → Run). It is the Postgres equivalent of what models/Lead.model.ts
-- used to declare in Mongoose, and it is safe to re-run: every statement is
-- guarded with IF NOT EXISTS.
--
-- Naming note: columns are snake_case, which is the Postgres convention and
-- also what the Supabase Table Editor renders most readably. The mapping to
-- the camelCase TypeScript field names happens in one place only —
-- services/leadStore.service.ts — so nothing else in the codebase has to know.
-- ============================================================================

create table if not exists public.leads (
  /* The application-level UUID generated by randomUUID() in leadStore.service.
     We supply it rather than letting Postgres default it, because the lead-alert
     email already quotes this id and staff paste it straight into the Table
     Editor's filter box. */
  id                uuid primary key,

  name              text        not null check (char_length(name) <= 120),

  /* text, never a numeric type: a leading zero or a "+91" prefix must survive. */
  whatsapp          text        not null check (char_length(whatsapp) <= 20),

  city              text        not null check (char_length(city) <= 120),

  product_type      text        not null
                    check (product_type in ('ON_GRID', 'HYBRID', 'OFF_GRID')),

  /* Module C's output on the On-Grid path, the resolved capacity on Hybrid.
     Null when the engine produced no capacity figure at all. */
  system_size_kw    numeric(10, 3)  check (system_size_kw is null or system_size_kw >= 0),

  /* Raw pre-rounding total from the pricing engine. The customer only ever
     sees Math.round() of it. numeric, not float — money must not drift. */
  estimate_cost_rs  numeric(14, 2)  not null check (estimate_cost_rs >= 0),

  /* Sales pipeline fields. Not produced by the website — these exist so staff
     can work the pipeline directly in the Supabase Table Editor. */
  status            text        not null default 'NEW'
                    check (status in ('NEW', 'CONTACTED', 'QUOTED', 'WON', 'LOST')),
  notes             text        not null default '' check (char_length(notes) <= 2000),
  source            text        not null default 'WEBSITE_CALCULATOR',

  /* timestamptz, never timestamp: stores an absolute instant, so IST display
     and UTC storage cannot disagree. */
  captured_at       timestamptz not null default now(),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- Admin list: newest first. This is the only sort the list view ever uses.
create index if not exists leads_captured_at_idx on public.leads (captured_at desc);

-- "Has this number contacted us before?"
create index if not exists leads_whatsapp_idx on public.leads (whatsapp);

-- "Open leads, newest first."
create index if not exists leads_status_captured_at_idx on public.leads (status, captured_at desc);


-- ---------------------------------------------------------------------------
-- updated_at maintenance
--
-- Mongoose did this for us via `timestamps: true`. Postgres needs it stated.
-- It matters because staff will edit `status` and `notes` by hand in the Table
-- Editor, and "when did someone last touch this lead?" is a question the sales
-- team will ask.
-- ---------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists leads_touch_updated_at on public.leads;
create trigger leads_touch_updated_at
  before update on public.leads
  for each row execute function public.touch_updated_at();


-- ---------------------------------------------------------------------------
-- Row Level Security — READ THIS BEFORE CHANGING IT
--
-- RLS is enabled and NO policies are created. That combination means:
--   • The `anon` and `authenticated` keys (the ones safe to ship in a browser)
--     can read and write NOTHING in this table. Correct: customer leads must
--     never be reachable from the public internet.
--   • The `service_role` key BYPASSES RLS entirely. That is the key the Node
--     backend uses, and it is why the backend can still insert and list leads.
--   • The Supabase Dashboard's Table Editor also bypasses RLS, so your staff
--     see everything normally when logged in.
--
-- The security of this table therefore rests on one thing: SUPABASE_SERVICE_ROLE_KEY
-- must live only in the backend's .env / host secrets, and must NEVER appear in
-- frontend code, a VITE_ variable, or a git commit.
-- ---------------------------------------------------------------------------
alter table public.leads enable row level security;
